# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Traindrop
email: your-email@domain.com
description: Enseigner le code et en particulier le front-end
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://traindrop.github.io/" # the base hostname & protocol for your site
repository: traindrop/traindrop.github.io

# Build settings
markdown: kramdown
permalink: /fiches/:slug/

# Exclusions
exclude:
  - "vendor"
